.TH "SHELLFETCH" "1" "VERSION" "SHELLFETCH" "VERSION"
.hy
.SH NAME
.PP
shellfetch \[en] Shell System Information Fetcher
.SH SYNOPSIS
.PP
\fI\,shellfetch --ascii_colors [numbers] --file [path/to/file]\/\fR
.SH DESCRIPTION
.PP
\f[B]shellfetch\f[R] is a fetch tool that gives system information along with a ascii header.
.SH GENERAL OPTIONS
.TP
\f[B]-v\f[R], \f[B]\--version\f[R]
Display a friendly version message.
.TP
\f[B]-c\f[R], \f[B]\--center\f[R]
Display the information in the center of the terminal.
.TP
\f[B]-f\f[R], \f[B]\--file\f[R] path/to/file
Set a file for the ascii header.
.TP
\f[B]-s\f[R], \f[B]\--source\f[R] path/to/file
Set a source for the config to read from.
.TP
\f[B]-ac\f[R], \f[B]\--ascii_colors\f[R] 1 2 3 4 5 6 7 8 9
Set the colors for the information posted.
.SH AUTHORS
The-Repo-Club.